### ISSUE TITLE
Witch version to start learning!!!

### ISSUE THREAD

**Issue by attora** [MarimerLLC/cslaforum#143]
Can someone help me to test asp.net or mvc project with CSLA framework . I downloaded the project via this link http://www.lhotka.net/cslanet/download.aspx.
Its very frustrating to find many compilation error . I find that there are many versions in CSLA and it brings a lot of confusion for a beginner. Especially with the new versions of MVC, ASP.net.

Now we have new version 4.6 so Where is the projecttraker for this version to test the samples...
I found that we have another frustrating version for CSLA in Codesmith generator. But when I try to test  the demo petshop I can't test it. 

Anyone can help with best method and step by step.

Thanks

**Comment by rockfordlhotka** [comment]
The industry has moved to using NuGet as the primary deployment technology for components like CSLA, and we've supported NuGet for many years now. About a year ago we switched to only doing NuGet releases.

You can download the code if you want to learn from it or whatever. But if you want to _use_ CSLA you should get the package(s) from NuGet within the context of your project in Visual Studio.

The current version of ProjectTracker is at the top level of the Samples folder: https://github.com/MarimerLLC/csla/tree/master/Samples/ProjectTracker

**Comment by rockfordlhotka** [comment]
I am assuming you found the [CSLA .NET releases](https://github.com/MarimerLLC/csla/releases) page?

There is only one current release per .NET platform version. So you should generally pick the highest CSLA version that works on your version of .NET. For nearly everything except old legacy code this means (today) version 4.6.300. That is also the default/current version you'll get if you just reference CSLA from NuGet.

**Comment by attora** [comment]
Sorry if I am litle confused!!!
Yes I get the release from the CSLA.NET. But Where is the MVC or ASP.net projects in this link
https://github.com/MarimerLLC/csla/tree/master/Samples/ProjectTracker?

I want to learn from this sample http://www.dnrtv.com/default.aspx?showNum=32 ,but how I can do that without facing a frustrating  and errors, I spent 2 days just to try run one asp.net or mvc example, but right now I am just facing compilation errors.

**Comment by rockfordlhotka** [comment]
I am sorry that you have caught me in a transition period. The most recent ProjectTracker sample doesn't include a web UI yet - there's an open issue for this to be done: https://github.com/MarimerLLC/csla/issues/506

I know that doesn't help.

The most recent _documentation_ and walkthrough for creating an ASP.NET MVC web site using CSLA is here: http://store.lhotka.net/using-csla-4-aspnet-mvc

That ebook was written in 2011, which might work to your benefit since it sounds like you are still using Visual Studio from that time period. The version of CSLA that was current at that time was 4.1, and the ProjectTracker from that time is here:
https://github.com/MarimerLLC/csla/tree/V4-1-0/Samples/NET/cs/ProjectTrackercs

There's no doubt in my mind that version of ProjectTracker won't compile with current CSLA - but it should compile with CSLA version 4.1:
https://github.com/MarimerLLC/csla/releases/tag/V4-1-0

I just dug into the archives, and there is an old download page that includes an installer for that version:
http://www.lhotka.net/cslanet/download.aspx

**Comment by attora** [comment]
Thanks for taking the time for this details.
I finally do your suggestion and can now compile a project with CSLA 4.1 version.

My problem now when I run the PtWebforms and PTWin I have this error in win or web forms!!
![image](https://cloud.githubusercontent.com/assets/7754535/13197795/104a131c-d7c6-11e5-8ddd-98ceb6d6b676.png)
